# Generated by Django 4.2.5 on 2023-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0019_rent_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='is_being_rented',
            field=models.BooleanField(default=False),
        ),
    ]
