# Generated by Django 4.2.5 on 2023-11-15 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0020_cycle_is_being_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 13, 38, 37, 994768)),
        ),
    ]
