# Generated by Django 4.2.5 on 2023-11-15 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0021_cycle_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 15, 15, 36, 133120)),
        ),
    ]
