# Generated by Django 4.2.5 on 2023-11-17 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0023_alter_cycle_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='sold_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_buyer', to='pedal.appuser'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 9, 40, 12, 618821)),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_owner', to='pedal.appuser'),
        ),
    ]
